### ISSUE TITLE
ennesimo errore di ieri 

### ISSUE THREAD

**Issue by artifix100** [Bbalduzz/Scuolabook-PDF-Downloader#3]
ciao mi sembra ennesimo errore di ieri . ho controllato ho eseguito di certo ultima edizione di oggi :)

PS C:\Users\piern\Downloads\Scuolabook-PDF-Downloader-main (2)\Scuolabook-PDF-Downloader-main> & C:/Users/piern/AppData/Local/Programs/Python/Python311/python.exe "c:/Users/piern/Downloads/Scuolabook-PDF-Downloader-main (2)/Scuolabook-PDF-Downloader-main/sbkDL.py"
Enter the book url: 
https://webapp.scuolabook.it/books/palumbo_w41038_w41035

[+] Book Found:
        - title: LIBERI di interpretare - ed. Rossa - vol. 1
        - author: R.Luperini, P.Cataldi, L.Marchiani, F.Marchese
        - isbn: 9788868896614
        - pages: 1062

Traceback (most recent call last):
  File "c:\Users\piern\Downloads\Scuolabook-PDF-Downloader-main (2)\Scuolabook-PDF-Downloader-main\sbkDL.py", line 84, in <module>
    dl()
  File "c:\Users\piern\Downloads\Scuolabook-PDF-Downloader-main (2)\Scuolabook-PDF-Downloader-main\sbkDL.py", line 60, in dl
    pages_url =  json.loads(pages_url)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piern\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piern\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piern\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
PS C:\Users\piern\Downloads\Scuolabook-PDF-Downloader-main (2)\Scuolabook-PDF-Downloader-main>

**Comment by Bbalduzz** [comment]
hey, interessante. Non riesco a riprodurre il tuo errore quindi mi servirebbe un aiuto da parte tua.
Puoi aggiungere nel tuo file `sbkDL.py` dopo la riga [`59`](https://github.com/Bbalduzz/Scuolabook-PDF-Downloader/blob/919174c0c78d281bfc0eb4fbb8f2148625cef6c6/sbkDL.py#L59) questo pezzetto:
`with open('manda_contenuto.txt', 'w') as f: f.write(pages_url)`?
Esegui lo script normalmente poi mandami il contenuto del file `manda_contenuto.txt` qui.

Grazie mille per la collaborazione :))

**Comment by artifix100** [comment]
ecco spero di aver fatto giusto
[manda_contenuto.txt](https://github.com/Bbalduzz/Scuolabook-PDF-Downloader/files/10339666/manda_contenuto.txt)

**Comment by artifix100** [comment]
![aggiuntariga](https://user-images.githubusercontent.com/66954952/210439001-3f03b643-a84a-4dec-8f16-7afaa5de5736.jpg)
 questa è la stringa aggiunta

**Comment by Bbalduzz** [comment]
perfetto, ha fatto tutto benissimo. Ora ci do una occhiata e ti faccio sapere ;)

**Comment by Bbalduzz** [comment]
Ho aggiornato lo script, dimmi se funziona o se il risultato non cambia.

**Comment by artifix100** [comment]
grazie degli sforzi per risolvere . allora intanto appena apro nuova versione appare questo messaggio nella console :
![ultima versionescript](https://user-images.githubusercontent.com/66954952/210639319-cf2f3827-6534-4be8-b427-072c175a0034.jpg)
poi a script avviato  appare questo messaggio di errore 
PS C:\Users\piern\OneDrive\Desktop\Scuolabook-PDF-Downloader-main> & C:/Users/piern/AppData/Local/Programs/Python/Python311/python.exe c:/Users/piern/OneDrive/Desktop/Scuolabook-PDF-Downloader-main/sbkDL.py
Enter the book url: 
https://webapp.scuolabook.it/books/palumbo_w41038_w41035

[+] Book Found:
        - title: LIBERI di interpretare - ed. Rossa - vol. 1
        - author: R.Luperini, P.Cataldi, L.Marchiani, F.Marchese
        - isbn: 9788868896614
        - pages: 1062

Traceback (most recent call last):
  File "c:\Users\piern\OneDrive\Desktop\Scuolabook-PDF-Downloader-main\sbkDL.py", line 92, in <module>
    dl()
  File "c:\Users\piern\OneDrive\Desktop\Scuolabook-PDF-Downloader-main\sbkDL.py", line 57, in dl 
    matches = re.search(check_pattern, pages_req)[0]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
PS C:\Users\piern\OneDrive\Desktop\Scuolabook-PDF-Downloader-main>

**Comment by Bbalduzz** [comment]
Ciao di nuovo! Innanzitutto grazie per la pazienza, ora (forse) il problema dovrebbe essere aggirato. Nel caso incontri altri problemi fammi sapere

**Comment by artifix100** [comment]
ciao questa funziona ! ma una domanda il pdf è semplicemente un insieme di immagini ad alta risoluzione  , non è testo .  poi un volume di mille pagine , me lo ha fatto solo fino a due terzi il rimanente pagine bianche , ma forse era stato un problema di linea internet, comunque anche così è uno script utilizzabile . grazie mille !
