### ISSUE TITLE
Libreria fitz non funziona - problema con il download

### ISSUE THREAD

**Issue by Nick806** [Bbalduzz/Scuolabook-PDF-Downloader#4]
Buongiorno,
ho provato ad utilizzare il programma ma ho avuto diversi intoppi nell'installazione delle diverse librerie.

Sono riuscito a sistemare tutto a parte quello che riguarda la libreria fitz.
Ogni volta che provo ad avviare il codice mi da questo problema:

![Immagine 2023-01-17 181924](https://user-images.githubusercontent.com/88904983/212967631-b399337f-7f4f-4d3d-84db-57c046b84ce9.png)

Traceback (most recent call last):
  File "C:\Users\zampr\Desktop\Estrazione di libri in pdf\Scuolabook-PDF-Downloader-main\sbkDL.py", line 6, in <module>
    import fitz
  File "C:\Users\zampr\AppData\Local\Programs\Python\Python311\Lib\site-packages\fitz\__init__.py", line 1, in <module>
    from frontend import *
ModuleNotFoundError: No module named 'frontend'

Ho controllato la pagina della libreria [(https://github.com/kastman/fitz)](https://github.com/kastman/fitz) ma non sono riuscito a capire se sia un problema di installazione della libreria o un problema di compatibilità con la versione di Python (versione 3.11.1).

Come posso risolvere?
Grazie in anticipo per l'aiuto

**Comment by Nick806** [comment]
Dopo diverse ricerche e tentativi sono riuscito a sistemare il problema.

E' bastato installare la libreria 'PyMuPDF' con ul comando **"pip install PyMuPDF"**
(non so perché prima non andasse)

Ora il programma funziona alla grande!

![Immagine 2023-01-17 185913](https://user-images.githubusercontent.com/88904983/212976017-bbd575e9-20de-4ced-b1fc-4a4f4f9a708d.png)

**Comment by Nick806** [comment]
Ciao di nuovo,
Sono riuscito ad incappare in un altro problema.
Mentre il programma sta scaricando il file si blocca quando arriva al 50%.

https://user-images.githubusercontent.com/88904983/212990588-6594f930-74dd-40e7-b8f4-96a45be621b1.mp4


Aprendo il file trovo che ha scaricato le pagine fino alla 288, dalla 289 in poi sono tutte bianche

![Immagine 2023-01-17 200706](https://user-images.githubusercontent.com/88904983/212990460-75f10d09-8e41-4808-a3c9-4ce1dce323d2.png)

Quale può essere il problema?

**Comment by Bbalduzz** [comment]
Hey ciao, grazie per aver segnalato il bug.
Il problema è nella creazione dei diversi link per le richieste delle pagine, infatti se guardi bene il download appena arriva al 50% scatta subito al 100% (cosa che non dovrebbe succedere). 
Le pagine bianche sono dovute al fatto che lo script se c'è un problema nel download della pagina, nella conversione o anche semplicemente l'url per la pagina è per qualche ragione errato, aggiunge una pagina bianca al posto di quella originale. 

Questo per dire che non è un problema tuo, ma un errore mio. Appena posso lo fixo :)
